version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB=icbox_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_passw
    secrets:
      - postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - local_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      -c max_connections=100 -c shared_buffers=${POSTGRES_SHARED_BUFFERS:-128MB} -c effective_cache_size=${POSTGRES_EFFECTIVE_CACHE_SIZE:-384MB} -c work_mem=4MB -c maintenance_work_mem=64MB
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7
    container_name: redis
    command: >
      sh -c "redis-server --requirepass redis_passw --maxmemory 256mb --maxmemory-policy allkeys-lru"
    secrets:
      - redis_password
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - local_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      - N8N_HOST=n8n.icbox.com.br
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=icbox_db
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=postgres_passw
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_PASSWORD=redis_passw
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console
      - N8N_LOG_FILE_MAXSIZE=10
      - N8N_LOG_FILE_MAXCOUNT=3
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    secrets:
      - postgres_password
      - redis_password
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "127.0.0.1:5678:5678"
    restart: unless-stopped
    networks:
      - local_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  redis_password:
    file: ./secrets/redis_password.txt

volumes:
  postgres_data:
    name: postgres_data
  redis_data:
    name: redis_data
  n8n_data:
    name: n8n_data

networks:
  local_network:
    driver: bridge
